mutation partyCreate ($data: PartyCreateInput!) {
  partyCreate (data: $data) 
}

query partyFind  {
  partyFind  {
    _id
    name
    organizerNickname 
    coordinate {
      latitude
      longitude
    }
    date
  }
}

query partySearch ($q: String) {
  partySearch (q: $q) {
    _id
    name
    organizerNickname 
  }
}

query partyGetById ($id: String!) {
  partyGetById (id: $id) {
    _id
    status
    name    
    organizer {
      nickname
    }
    availability
    address
    date
    openBar
    description
    attenders {
      _id
    }
    attendersCount 
    allowInvites
    isAttender
    isOrganizer
  }
}

query partySearchAttenders ($data: PartySearchAttendersInput!) {
  partySearchAttenders (data: $data) {
    _id
    nickname    
    fullName
  }
}

