query partySearch ($q: String) {
  partySearch (q: $q) {
    _id
    name
    organizer {
      nickname
    }
    coordinates {
      latitude
      longitude
    }
    date
  }
}

query partyGetById ($id: String!) {
  partyGetById (id: $id) {
    _id
    name    
    organizer {
      nickname
    }
    address
    date
    openBar
    description

    attenders {
      _id
    }
    attendersCount 
    isAttender
  }
}

query partySearchAttenders ($data: PartySearchAttendersInput!) {
  partySearchAttenders (data: $data) {
    _id
    nickname    
    fullName
  }
}

