mutation signUp ($data: AuthSignUpInput!) {
  signUp (data: $data) {
    userId
    accessToken
    refreshToken
  }
}

mutation signIn ($data: AuthSignInInput!) {
  signIn (data: $data) {
    userId
    accessToken
    refreshToken
  }
}

mutation signInFromRefreshToken  {
  signInFromRefreshToken  {
    userId
    accessToken
    refreshToken
  }
}

mutation generateRecoveryCode ($data: AuthGenerateRecoveryCodeInput!) {
  generateRecoveryCode(data: $data)
}

mutation recoverPassword ($data: AuthRecoverPasswordInput!) {
  recoverPassword(data: $data)
}

mutation changePassword ($data: AuthChangePasswordInput!) {
  changePassword(data: $data)
}
