query userSearch ($q: String) {
  userSearch(q: $q) {
    _id
    nickname
    fullName
    pictureId
  }
}

query userGet ($data: UserGetInput!) {
  userGet (data: $data) {
    _id
    nickname
    fullName
    pictureId
    instagramUsername

    followersCount
    followingCount
    attendedPartiesCount 

    isFollowing
    isFollower
  }
}

query userGetFollowingById ($id: String!) {
  userGetFollowingById(id: $id) {
    _id
    nickname
    fullName
    pictureId
  }
}

query userGetFollowersById ($id: String!) {
  userGetFollowersById(id: $id) {
    _id
    nickname
    fullName
    pictureId
  }
}

query userGetAttendedPartiesById ($id: String!) {
  userGetAttendedPartiesById(id: $id) {
    _id
    name
    organizerNickname
  }
}

query userSearchFollowersToInvite ($data: UserSearchFollowersToInviteInput!) {
  userSearchFollowersToInvite (data: $data) {
    _id
    nickname    
    fullName
    pictureId
  }
}

query userCheckPartyValidating {
  userCheckPartyValidating
}

mutation userChangeFollowingState ($data: UserChangeFollowingStateInput!) {
  userChangeFollowingState (data: $data)
}

mutation userChangeAttendingState ($data: UserChangeAttendingStateInput!) {
  userChangeAttendingState (data: $data)
}

mutation userSendPartyInvite ($data: UserSendPartyInviteInput!) {
  userSendPartyInvite (data: $data)
}

mutation userEdit ($data: UserEditInput!) {
  userEdit(data: $data)   
}

mutation userDelete ($data: UserDeleteInput!) {
  userDelete(data: $data)   
}

